# Generated by Django 4.0.2 on 2022-02-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='owner',
            name='age',
            field=models.IntegerField(),
        ),
    ]
